# This is a basic workflow to help you get started with Actions

name: publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - "book/**"
      - ".github/workflows/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-jb:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: ["3.8"]
      fail-fast: false # Don't cancel all jobs if one fails

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout-repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: make deps
        working-directory: ./book

      - name: Build Jupyter-Book with warnings raised to errors
        run: make strict
        working-directory: ./book

      - name: Run pathways script
        run: make pathways
        working-directory: ./book

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: book/website/_build/html
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
